# =============SERVER==================
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

app:
  transactionDateAge: 30

server:
  port: ${PORT:5000}

# ============ACTUATOR===================
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
